
Drop table if exists FAITS_VENTES  ;
Drop table if exists DIM_MAGASIN  ;
Drop table if exists COURS  ;
Drop table if exists DEVISE  ;
Drop table if exists DIM_ENSEIGNE  ;
Drop table if exists DIM_DEPARTEMENT  ;
Drop table if exists DIM_FAMILLE_PRODUIT  ;
Drop table if exists DIM_GEOGRAPHIQUE_ADMIN  ;
Drop table if exists DIM_GEOGRAPHIQUE_COM  ;
Drop table if exists DIMS  ;
Drop table if exists FRANCE_DEPARTEMENTS  ;
Drop table if exists PROFIL  ;
Drop table if exists SECURITE  ;
Drop table if exists UTILISATEUR  ;

CREATE TABLE COURS(	
	ID_DEVISE 					int 			NOT NULL ,
	MOIS 						int 			NOT NULL ,
	ANNEE 						int 			NOT NULL ,
	COURS 						int,
	DATEMAJ_COURS				DATE,
	PRIMARY KEY (ID_DEVISE, MOIS, ANNEE)
) ;

CREATE TABLE DEVISE(	
	ID_DEVISE 					int 			NOT NULL ,
	LIB_DEVISE 					VARCHAR(10) 	NOT NULL ,
	ISOCODE 					VARCHAR(3) 		NOT NULL ,
	SYMBOLE 					VARCHAR(1),
	FORMAT_BO 					VARCHAR(20),
	COURS_FIXE 					int,
	DATEMAJ_DEVISE 				DATE,
	PRIMARY KEY (ID_DEVISE)
);

CREATE TABLE DIM_DEPARTEMENT(	
	ID_DEPARTEMENT 				int 			NOT NULL ,
	CODE_DEPARTEMENT 			VARCHAR(2) 		NOT NULL ,
	LIB_DEPARTEMENT 			VARCHAR(32) 	NOT NULL ,
	ID_REGION_ADMIN1 			int 			NOT NULL ,
	ID_REGION_ADMIN2 			int 			NOT NULL ,
	ID_REGION_COM 				int 			NOT NULL ,
	DATEMAJ_DEP 				DATE,
	PRIMARY KEY (ID_DEPARTEMENT)
);

CREATE TABLE DIM_ENSEIGNE(	
	ID_ENSEIGNE 				int 			NOT NULL ,
	LIB_ENSEIGNE 				VARCHAR(32) 	NOT NULL ,
	FICHIER_IMAGE_LOGO_ENSEIGNE VARCHAR(20),
	DATEMAJ_ENSEIGNE 			DATE,
	PRIMARY KEY (ID_ENSEIGNE)
) ;

CREATE TABLE DIM_FAMILLE_PRODUIT(	
	ID_FAMILLE_PRODUIT 			int 			NOT NULL ,
	LIB_FAMILLE_PRODUIT 		VARCHAR(32) 	NOT NULL ,
	DATEMAJ_FAMPROD 			DATE,
	PRIMARY KEY (ID_FAMILLE_PRODUIT)
) ;

CREATE TABLE DIM_GEOGRAPHIQUE_ADMIN(	
	ID_REGION_ADMIN 			int 			NOT NULL ,
	LIB_REGION_ADMIN 			VARCHAR(50) 	NOT NULL ,
	DATE_DEBUT_VALID_ADMIN 		DATE 			NOT NULL ,
	DATE_FIN_VALID_ADMIN 		DATE,
	FICHIER_IMAGE_CARTE_REGADM 	VARCHAR(50),
	DATEMAJ_GEO_ADMIN 			DATE,
	PRIMARY KEY (ID_REGION_ADMIN)
) ;

CREATE TABLE DIM_GEOGRAPHIQUE_COM(	
	ID_REGION_COM 				int 			NOT NULL ,
	LIB_REGION_COM 				VARCHAR(50) 	NOT NULL ,
	DATE_DEBUT_VALID_COM 		DATE 			NOT NULL ,
	DATE_FIN_VALID_COM 			DATE,
	FICHIER_IMAGE_CARTE_REGCOM VARCHAR(20),
	DATEMAJ_GEO_COM 			DATE,
	PRIMARY KEY (ID_REGION_COM)
) ;

CREATE TABLE DIM_MAGASIN(	
	ID_MAGASIN 					int 			NOT NULL ,
	ID_ENSEIGNE 				int 			NOT NULL ,
	ACTIF 						VARCHAR(6),
	DATE_OUVERTURE 				DATE,
	DATE_FERMETURE 				DATE,
	DATE_MAJ 					DATE,
	EMPLACEMENTS 				VARCHAR(32),
	NB_CAISSES 					int,
	VILLE 						VARCHAR(32),
	DEP 						int,
	FICHIER_IMAGE_CARTE_MAGASIN VARCHAR(20),
	PRIMARY KEY (ID_MAGASIN)
) ;

CREATE TABLE DIMS(	
	IDS 						VARCHAR(8) 		NOT NULL ,
	MOIS 						int 			NOT NULL ,
	LIB_MOIS 					VARCHAR(10) 	NOT NULL ,
	TRIMESTRE 					int 			NOT NULL ,
	SEMESTRE 					int 			NOT NULL ,
	ANNEE 						int 			NOT NULL ,
	PRIMARY KEY (IDS)
) ;

CREATE TABLE FAITS_VENTES(	
	ID_MAGASIN 					int 			NOT NULL ,
	ID_FAMILLE_PRODUIT 			int 			NOT NULL ,
	IDS 						VARCHAR(8) 		NOT NULL ,
	VENTES_OBJECTIF 			int,
	VENTES_REEL 				int,
	CA_OBJECTIF 				int,
	CA_REEL 					int,
	MARGE_OBJECTIF 				int,
	MARGE_REEL 					int,
	DATE_MAJ 					DATE 			NOT NULL ,
	PRIMARY KEY (ID_MAGASIN, ID_FAMILLE_PRODUIT, IDS),

	CONSTRAINT FK_FP FOREIGN KEY (ID_FAMILLE_PRODUIT)
	REFERENCES DIM_FAMILLE_PRODUIT (ID_FAMILLE_PRODUIT) ,
	CONSTRAINT FK_FT FOREIGN KEY (IDS)
	REFERENCES DIMS (IDS) ,
	CONSTRAINT FK_FM FOREIGN KEY (ID_MAGASIN)
	REFERENCES DIM_MAGASIN (ID_MAGASIN)
) ;


CREATE TABLE FRANCE_DEPARTEMENTS(	
	CODE_DEPT 					VARCHAR(8) 		NOT NULL ,
	LIB_DEPARTEMENT 			VARCHAR(128),
	ID_REGION_ADMIN1 			int,
	ID_REGION_ADMIN2 			int,
	ID_REGION_COM 				int,
	PRIMARY KEY (CODE_DEPT)
) ;

CREATE TABLE PROFIL(	
	ID_PROFIL 					int 			NOT NULL ,
	LIB_PROFIL 					VARCHAR(50) 	NOT NULL ,
	TYPE_ZONE 					int,
	ID_ZONE 					int,
	USERNAME_BO 				VARCHAR(20),
	PASSWORD_BO 				VARCHAR(20),
	DATEMAJ_PROFIL 				DATE,
	PRIMARY KEY (ID_PROFIL)
) ;

CREATE TABLE SECURITE(	
	ID_MAGASIN 					int 			NOT NULL ,
	ID_PROFIL 					int 			NOT NULL ,
	ONGLET 						int 			NOT NULL ,
	DATEMAJ_SECURITE DATE,
	PRIMARY KEY (ID_MAGASIN, ID_PROFIL, ONGLET)
);

CREATE TABLE UTILISATEUR(	
	ID 							int 			NOT NULL ,
	NOM 						VARCHAR(50) 	NOT NULL ,
	PRENOM 						VARCHAR(50) 	NOT NULL ,
	USERNAME 					VARCHAR(50) 	NOT NULL ,
	PASSWORD 					VARCHAR(10) 	NOT NULL ,
	MAIL 						VARCHAR(100) 	NOT NULL ,
	ID_PROFIL 					int 			NOT NULL ,
	DATEMAJ_USER 				DATE,
	PRIMARY KEY (ID)
);
