Drop table if exists FAITS_VENTES;
Drop table if exists DIM_MAGASIN;
Drop table if exists COURS;
Drop table if exists  DEVISE ;
Drop table if exists  DIM_ENSEIGNE ;
Drop table if exists  DIM_DEPARTEMENT ;
Drop table if exists  DIM_FAMILLE_PRODUIT ;
Drop table if exists  DIM_GEOGRAPHIQUE_ADMIN ;
Drop table if exists  DIM_GEOGRAPHIQUE_COM ;
Drop table if exists  DIMS ;
Drop table if exists  FRANCE_DEPARTEMENTS ;
Drop table if exists  PROFIL ;
Drop table if exists  SECURITE ;
Drop table if exists  UTILISATEUR ;


CREATE TABLE COURS(
	ID_DEVISE 		INT NOT NULL ,
	MOIS 					INT NOT NULL ,
	ANNEE  				INT NOT NULL ,
	COURS  				INT,
	DATEMAJ_COURS DATE,
	PRIMARY KEY (ID_DEVISE, MOIS, ANNEE)
);

CREATE TABLE DEVISE(
	ID_DEVISE 			INT			 			NOT NULL ,
	LIB_DEVISE 			VARCHAR(10) 	NOT NULL ,
	ISOCODE 				VARCHAR(3) 		NOT NULL ,
	SYMBOLE 				VARCHAR(1),
	FORMAT_BO 			VARCHAR(20),
	COURS_FIXE 			INT,
	DATEMAJ_DEVISE	DATE,
	PRIMARY KEY (ID_DEVISE)
);

CREATE TABLE DIM_DEPARTEMENT(
	ID_DEPARTEMENT 		INT 					NOT NULL ,
	CODE_DEPARTEMENT 	VARCHAR(2) 		NOT NULL ,
	LIB_DEPARTEMENT 	VARCHAR(32) 	NOT NULL ,
	ID_REGION_ADMIN1 	INT 					NOT NULL ,
	ID_REGION_ADMIN2	INT 					NOT NULL ,
	ID_REGION_COM 		INT 					NOT NULL ,
	DATEMAJ_DEP 			DATE,
	PRIMARY KEY (ID_DEPARTEMENT)
);

CREATE TABLE DIM_ENSEIGNE(
	ID_ENSEIGNE 				 				INT 					NOT NULL ,
	LIB_ENSEIGNE 								VARCHAR(32) 	NOT NULL ,
	FICHIER_IMAGE_LOGO_ENSEIGNE VARCHAR(20),
	DATEMAJ_ENSEIGNE 						DATE,
	PRIMARY KEY (ID_ENSEIGNE)
) ;

CREATE TABLE DIM_FAMILLE_PRODUIT(
	ID_FAMILLE_PRODUIT 	INT 				NOT NULL ,
	LIB_FAMILLE_PRODUIT	VARCHAR(32)	NOT NULL ,
	DATEMAJ_FAMPROD 		DATE,
	PRIMARY KEY (ID_FAMILLE_PRODUIT)
) ;

CREATE TABLE DIM_GEOGRAPHIQUE_ADMIN(
	ID_REGION_ADMIN 			 			INT 				NOT NULL ,
	LIB_REGION_ADMIN 						VARCHAR(50)	NOT NULL ,
	DATE_DEBUT_VALID_ADMIN 			DATE 				NOT NULL ,
	DATE_FIN_VALID_ADMIN				DATE,
	FICHIER_IMAGE_CARTE_REGADM	VARCHAR(50),
	DATEMAJ_GEO_ADMIN 					DATE,
	PRIMARY KEY (ID_REGION_ADMIN)
) ;

CREATE TABLE DIM_GEOGRAPHIQUE_COM(
	ID_REGION_COM 				 			INT 				NOT NULL ,
	LIB_REGION_COM 							VARCHAR(50) NOT NULL ,
	DATE_DEBUT_VALID_COM 				DATE 				NOT NULL ,
	DATE_FIN_VALID_COM 					DATE,
	FICHIER_IMAGE_CARTE_REGCOM 	VARCHAR(20),
	DATEMAJ_GEO_COM 						DATE,
	PRIMARY KEY (ID_REGION_COM)
) ;

CREATE TABLE DIM_MAGASIN(
	ID_MAGASIN 					 				INT 				NOT NULL ,
	ID_ENSEIGNE 				 				INT 				NOT NULL ,
	ACTIF 											VARCHAR(6),
	DATE_OUVERTURE 							DATE,
	DATE_FERMETURE 							DATE,
	DATE_MAJ 										DATE,
	EMPLACEMENTS 								VARCHAR(32),
	NB_CAISSES 					 				INT,
	VILLE 											VARCHAR(32),
	DEP  												INT,
	FICHIER_IMAGE_CARTE_MAGASIN	VARCHAR(20),
	PRIMARY KEY (ID_MAGASIN)
) ;

CREATE TABLE DIMS(
	IDS 			VARCHAR(8) 	NOT NULL ,
	MOIS  		INT 				NOT NULL ,
	LIB_MOIS 	VARCHAR(10) NOT NULL ,
	TRIMESTRE	INT 				NOT NULL ,
	SEMESTRE 	INT 				NOT NULL ,
	ANNEE  		INT 				NOT NULL ,
	PRIMARY KEY (IDS)
) ;

CREATE TABLE FAITS_VENTES(
	ID_MAGASIN 					INT 				NOT NULL ,
	ID_FAMILLE_PRODUIT	INT 				NOT NULL ,
	ID_TEMPS 					VARCHAR(8)	NOT NULL ,
	VENTES_OBJECTIF 		INT,
	VENTES_REEL 				INT,
	CA_OBJECTIF 				INT,
	CA_REEL 					 	INT,
	MARGE_OBJECTIF 			INT,
	MARGE_REEL 					INT,
	DATE_MAJ 						DATE 				NOT NULL ,
	PRIMARY KEY (ID_MAGASIN, ID_FAMILLE_PRODUIT, ID_TEMPS),
	CONSTRAINT FK_FP FOREIGN KEY (ID_FAMILLE_PRODUIT)	REFERENCES DIM_FAMILLE_PRODUIT (ID_FAMILLE_PRODUIT) ,
	CONSTRAINT FK_FT FOREIGN KEY (ID_TEMPS) REFERENCES DIMS (ID_TEMPS) ,
	CONSTRAINT FK_FM FOREIGN KEY (ID_MAGASIN)	REFERENCES DIM_MAGASIN (ID_MAGASIN)
) ;


CREATE TABLE FRANCE_DEPARTEMENTS(
	CODE_DEPT 				VARCHAR(8) 		NOT NULL ,
	LIB_DEPARTEMENT 	VARCHAR(128),
	ID_REGION_ADMIN1	INT,
	ID_REGION_ADMIN2 	INT,
	ID_REGION_COM 		INT,
	PRIMARY KEY (CODE_DEPT)
) ;

CREATE TABLE PROFIL(
	ID_PROFIL 			INT 				NOT NULL ,
	LIB_PROFIL 			VARCHAR(50)	NOT NULL ,
	TYPE_ZONE 			INT,
	ID_ZONE 				INT,
	USERNAME_BO 		VARCHAR(20),
	PASSWORD_BO 		VARCHAR(20),
	DATEMAJ_PROFIL	DATE,
	PRIMARY KEY (ID_PROFIL)
) ;

CREATE TABLE SECURITE(
	ID_MAGASIN 				INT 	NOT NULL ,
	ID_PROFIL 				INT 	NOT NULL ,
	ONGLET  					INT		NOT NULL ,
	DATEMAJ_SECURITE	DATE,
	PRIMARY KEY (ID_MAGASIN, ID_PROFIL, ONGLET)
);

CREATE TABLE UTILISATEUR(
	ID 	 					INT 					NOT NULL ,
	NOM 					VARCHAR(50) 	NOT NULL ,
	PRENOM 				VARCHAR(50) 	NOT NULL ,
	USERNAME			VARCHAR(50) 	NOT NULL ,
	PASSWORD 			VARCHAR(10) 	NOT NULL ,
	MAIL 					VARCHAR(100) 	NOT NULL ,
	ID_PROFIL 		INT 					NOT NULL ,
	DATEMAJ_USER	DATE,
	PRIMARY KEY (ID)
);
